### ISSUE TITLE
generated JsonObjectMapper code for inheritance doesn't compile

### ISSUE THREAD

**Issue by ellsworthrw** [bluelinelabs/LoganSquare#108]
@JsonObject
public class AssetDetails {

@JsonObject
public class WatchlistEntitlement extends AssetDetails implements AssetEntitlement, Asset {
}

generates compile error on first line of class:

public final class WatchlistEntitlement$$JsonObjectMapper extends JsonMapper<WatchlistEntitlement> {
  private static JsonMapper<AssetDetails> parentObjectMapper = COM_MOVENETWORKS_MODEL_ASSETDETAILS__JSONOBJECTMAPPER;

I think it should be:

public final class WatchlistEntitlement$$JsonObjectMapper extends JsonMapper<WatchlistEntitlement> {
  private static JsonMapper<AssetDetails> parentObjectMapper = JsonMapperLoaderImpl.COM_MOVENETWORKS_MODEL_ASSETDETAILS__JSONOBJECTMAPPER;

FYI: same issue in:

  public void ensureParent() {
    if (parentObjectMapper == null) {
      parentObjectMapper = COM_MOVENETWORKS_MODEL_ASSETDETAILS__JSONOBJECTMAPPER;
    }
  }

**Comment by EricKuck** [comment]
Any chance you have a sample project that can reproduce this issue? We've
used this in lots of apps and haven't had any similar problems.

**Comment by eirnym** [comment]
```
@JsonObject
public class Animal {
  @JsonField
  public String name;
}

@JsonObject
public class Cat extends Animal {
  @JsonField
  public String color;
}
```

the workaround is:
```
@JsonObject
public class Animal<E> {
  @JsonField
  public String name;
}

@JsonObject
public class Cat extends Animal {
  @JsonField
  public String color;
}
```
because it generates and not constant:
```
private JsonMapper<Animal> parentObjectMapper = LoganSquare.mapperFor(new ParameterizedType< Animal>() {});
```

**Comment by EricKuck** [comment]
Sorry, there was a typo on one line. This is now fixed in 1.3.2.

**Comment by ellsworthrw** [comment]
I moved to 1.3.2 and it still does not compile. eirnym workaround is the only way to get it to compile.

**Comment by EricKuck** [comment]
What's the issue with compiling? The issue you posted about was fixed, so I'm guessing it must be something else?

**Comment by ellsworthrw** [comment]
The same issue still exists. I added the following to the benchmark demo app:
package com.bluelinelabs.logansquare.demo.model;

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;

@JsonObject
public class Animal {
    @JsonField
    public String name;
}

@JsonObject
public class Cat extends Animal {
    @JsonField
    public String color;
}

This produces the following which does not compile:

package com.bluelinelabs.logansquare.demo.model;

import com.bluelinelabs.logansquare.JsonMapper;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

@SuppressWarnings("unsafe,unchecked")
public final class Cat$$JsonObjectMapper extends JsonMapper<Cat> {
  private static JsonMapper<Animal> parentObjectMapper = COM_BLUELINELABS_LOGANSQUARE_DEMO_MODEL_ANIMAL__JSONOBJECTMAPPER;

  @Override
  public Cat parse(JsonParser jsonParser) throws IOException {
    Cat instance = new Cat();
    if (jsonParser.getCurrentToken() == null) {
      jsonParser.nextToken();
    }
    if (jsonParser.getCurrentToken() != JsonToken.START_OBJECT) {
      jsonParser.skipChildren();
      return null;
    }
    while (jsonParser.nextToken() != JsonToken.END_OBJECT) {
      String fieldName = jsonParser.getCurrentName();
      jsonParser.nextToken();
      parseField(instance, fieldName, jsonParser);
      jsonParser.skipChildren();
    }
    return instance;
  }

  @Override
  public void parseField(Cat instance, String fieldName, JsonParser jsonParser) throws IOException {
    if ("color".equals(fieldName)) {
      instance.color = jsonParser.getValueAsString(null);
    } else {
      parentObjectMapper.parseField(instance, fieldName, jsonParser);
    }
  }

  @Override
  public void serialize(Cat object, JsonGenerator jsonGenerator, boolean writeStartAndEnd) throws IOException {
    if (writeStartAndEnd) {
      jsonGenerator.writeStartObject();
    }
    if (object.color != null) {
      jsonGenerator.writeStringField("color", object.color);
    }
    parentObjectMapper.serialize(object, jsonGenerator, false);
    if (writeStartAndEnd) {
      jsonGenerator.writeEndObject();
    }
  }

  public void ensureParent() {
    if (parentObjectMapper == null) {
      parentObjectMapper = COM_BLUELINELABS_LOGANSQUARE_DEMO_MODEL_ANIMAL__JSONOBJECTMAPPER;
    }
  }
}

**Comment by EricKuck** [comment]
1.3.2 doesn't generate the ensureParent method anymore, so this must still be using the old version. Make sure you're updating the version number for both the annotation processor and the core library.

**Comment by ellsworthrw** [comment]
Yep, I did not update the apt one. However, once I did that and did a rebuild then I get a crash of:

Error:Exception while processing Json classes. Stack trace incoming:
  java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V
  	at com.bluelinelabs.logansquare.processor.JsonMapperLoaderInjector.addAllProjectMappers(JsonMapperLoaderInjector.java:137)
  	at com.bluelinelabs.logansquare.processor.JsonMapperLoaderInjector.getTypeSpec(JsonMapperLoaderInjector.java:79)
  	at com.bluelinelabs.logansquare.processor.JsonMapperLoaderInjector.getJavaClassFile(JsonMapperLoaderInjector.java:63)
  	at com.bluelinelabs.logansquare.processor.JsonAnnotationProcessor.process(JsonAnnotationProcessor.java:75)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
  	at com.sun.tools.javac.main.Main.compile(Main.java:439)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
  	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
  	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
  	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
  	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
  	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
  	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:137)
  	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:91)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:606)
  	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
  	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
  	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
  	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
  	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
  	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
  	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
  	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
  	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
  	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:208)
  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:186)
  	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
  	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
  	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:111)
  	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
  	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
  	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
  	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
  	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
  	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
  	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
  	at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174)
  	at org.gradle.internal.Factories$1.create(Factories.java:22)
  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
  	at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
  	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:171)
  	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
  	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
  	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
  	at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
  	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
  	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
  	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
  	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
  	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
  	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
  	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
  	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
  	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
  	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
  	at org.gradle.util.Swapper.swap(Swapper.java:38)
  	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
  	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
  	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
  	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
  	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  	at java.lang.Thread.run(Thread.java:745)

**Comment by EricKuck** [comment]
Guess I assumed everyone was using jdk 8 by now, which probably wasn't a great assumption. I just published another version, 1.3.3, which works on jdk 6 and 7.

**Comment by ellsworthrw** [comment]
I have a clean build now with v1.3.3
Thanks.
