### ISSUE TITLE
com.bluelinelabs.logansquare.NoSuchMapperException:

### ISSUE THREAD

**Issue by androiddevelop** [bluelinelabs/LoganSquare#71]
I write simple code, but it's not working.

Bean.class
``````
package me.codeboy.lyd.test;

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;

/**
 * Created by yuedong on 6/26/15.
 */

@JsonObject
public class Bean {

    @JsonField
    public String name ;
}
`````

Test1.class
````
package me.codeboy.lyd.test;

import com.bluelinelabs.logansquare.LoganSquare;
import com.google.gson.Gson;

import java.io.IOException;

/**
 * Created by YD on 5/25/15.
 */
public class Test1 {
    public static void main(String[] args) throws IOException {
        test();
    }

    public static void test() throws IOException {
        Bean bean = new Bean();
        bean.name = "name";


        Gson gson = new Gson();
        String source = gson.toJson(bean, Bean.class);

        System.out.println(source);

        LoganSquare.parse(source, Bean.class);

    }
}
````
I use Gson to generate json string , then I use LoganSquare to deserialize the json string, finally, the exception occurs. The exception is as follow:
```
{"name":"name"}
Exception in thread "main" com.bluelinelabs.logansquare.NoSuchMapperException: Class me.codeboy.lyd.test.Bean could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
	at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:165)
	at com.bluelinelabs.logansquare.LoganSquare.parse(LoganSquare.java:44)
	at me.codeboy.lyd.test.Test1.test(Test1.java:26)
	at me.codeboy.lyd.test.Test1.main(Test1.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: me.codeboy.lyd.test.Bean$$JsonObjectMapper
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:161)
	... 8 more
```

**Comment by EricKuck** [comment]
Can you attach your build.gradle file? It's almost guaranteed that's the issue.

**Comment by androiddevelop** [comment]
```
group 'me.codeboy.lyd'
version '1.0.0'

apply plugin: 'java'

repositories {
    mavenCentral()
    maven {
        url 'http://repo1.maven.org/maven2'
    }

    mavenLocal()
}

dependencies {
    testCompile ('junit:junit:4.11')
    compile ('org.jsoup:jsoup:1.8.2')
    compile ('me.codeboy.common:base:1.0.1')
    compile('com.alibaba:fastjson:1.2.6')
    compile 'com.fasterxml.jackson.core:jackson-core:2.5.1'
    compile ('com.google.code.gson:gson:2.3.1')
}
```
I add the LoganSquare core code into my project , because the newest version in maven repo is 1.0.6.

**Comment by androiddevelop** [comment]
.
├── main
│   ├── java
│   │   ├── com
│   │   │   └── bluelinelabs
│   │   │       └── logansquare
│   │   │           ├── Constants.java
│   │   │           ├── JsonMapper.java
│   │   │           ├── LoganSquare.java
│   │   │           ├── NoSuchMapperException.java
│   │   │           ├── NoSuchTypeConverterException.java
│   │   │           ├── annotation
│   │   │           │   ├── JsonField.java
│   │   │           │   ├── JsonIgnore.java
│   │   │           │   ├── JsonObject.java
│   │   │           │   ├── OnJsonParseComplete.java
│   │   │           │   └── OnPreJsonSerialize.java
│   │   │           └── typeconverters
│   │   │               ├── BooleanBasedTypeConverter.java
│   │   │               ├── CalendarTypeConverter.java
│   │   │               ├── DateTypeConverter.java
│   │   │               ├── DefaultCalendarConverter.java
│   │   │               ├── DefaultDateConverter.java
│   │   │               ├── DefaultDateFormatter.java
│   │   │               ├── DoubleBasedTypeConverter.java
│   │   │               ├── FloatBasedTypeConverter.java
│   │   │               ├── IntBasedTypeConverter.java
│   │   │               ├── LongBasedTypeConverter.java
│   │   │               ├── StringBasedTypeConverter.java
│   │   │               └── TypeConverter.java
│   │   └── me
│   │       └── codeboy
│   │           └── lyd
│   │               ├── bean
│   │               │   ├── Res.java
│   │               │   ├── Res2.java
│   │               │   ├── Stu.java
│   │               │   └── Stu2.java
│   │               └── test
│   │                   ├── Bean.java
│   │                   ├── Test.java
│   │                   └── Test2.java
│   └── resources
└── test
    ├── java
    │   └── me
    │       └── codeboy
    │           └── lyd
    │               └── test
    │                   └── junit
    │                       └── Test.java
    └── resources

21 directories, 30 files

**Comment by EricKuck** [comment]
The reason this library is able to so efficiently is because it generates code at compile time. You can't simply include the source files and expect it to work the way a run-time library like GSON does. 

If you switch to JCenter from MavenCentral (which Google recommends doing anyway), you can get the 1.1.0 library. Just switch `mavenCentral()` to `jcenter()` in your build.gradle file.

**Comment by EricKuck** [comment]
I just pushed the library to Maven Central, so you don't really have to switch to JCenter if you don't want to, although it's still recommended.

**Comment by androiddevelop** [comment]
problem remain.
I use LoganSquare by build.gradle 
```
 compile 'com.bluelinelabs:logansquare:1.1.0'
```
and delete the source code of LoganSquare, but the code still does not work. The Exception is same .

I  read the example of BenchmarkDemo， I can not find  a different usage.

**Comment by EricKuck** [comment]
You're still just adding the runtime library. Check out the example in the
readme file to see how to do it, or look at the sample like you mentioned.
You have to use apt.

>

**Comment by androiddevelop** [comment]
Thanks, it works

**Comment by glenaries03** [comment]
can't make it work :( 

just a simple json 

{
  "valid_android_clients":[
    "1.0.0"
  ],
  "languages":[
    {
      "code": "en_us",
      "short_code": "en",
      "name": "English",
      "updated_at": "2017-11-29 11:02:25"
    }
  ]
}

can you show me how to do the model?
i followed the instruction but still receiving error : Perhaps it hasn't been annotated with @JsonObject?

**Comment by glenaries03** [comment]
this is the model 

@JsonObject
public class LanguageModel {

    @JsonField(name = "languages")
    public List<Languages> languages;

    @JsonObject
    public class Languages{

        @JsonField(name = "code")
        public String languageCode;

        @JsonField(name = "short_code")
        public String languageShortCode;

        @JsonField(name = "name")
        public String languageName;

        @JsonField(name = "updated_at")
        public String languageUpdatedAt;

    }

}
